[versions]
kotlin = "2.1.0"
dokka = "1.9.20"
nexusPublishing = "2.0.0"
detekt = "1.23.7"
bouncyCastle = "1.79"
bcrypt = "0.10.2"
commonsCodec = "1.17.1"
testContainers = "1.20.4"
postgresqlDriver = "42.7.4"
slf4j = "2.0.16"

[libraries]
bouncyCastleBcpg = { module = "org.bouncycastle:bcpg-jdk18on", version.ref = "bouncyCastle" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
commonsCodec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
testContainersJunitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testContainers" }
testContainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testContainers" }
postgresqlDriver = { module = "org.postgresql:postgresql", version.ref = "postgresqlDriver" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexusPublishing = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublishing" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
